name: Publish to NuGet

on:
  push:
    branches:
      - main
      - release/*

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Setup NerdBank
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Package
      run: dotnet pack --no-build -c Release src/Doctr.Diagnostics/Doctr.Diagnostics.csproj -o .
    - name: Publish
      run: dotnet nuget push *.nupkg -k ${{secrets.NUGET_API_KEY}} --skip-duplicate -s https://api.nuget.org/v3/index.json
      
